import QuadraticFormsSobolev.LebesgueDiff
import QuadraticFormsSobolev.Section1

/-!
# The limit procedure of Section 3.2

Section 3.2 passes from the discrete inequality `(discret)` to the continuous
one by letting `h → 0`. On the left it uses Fatou. On the right it asserts

> For the right hand side in (discret) this implies with help of dominated
> convergence … `∫ g_h → ∫ g`

without exhibiting a dominating function, and none is available unconditionally
(see the README).

This file supplies the missing ingredient in the form the argument can use. The
point is that a *varying* dominant suffices, and that the tile-averaging
operator `tileAvg` provides one: it is an averaging (conditional expectation)
operator, so it **preserves the integral exactly** (`lintegral_tileAvg`), and it
converges almost everywhere by Lemma 7.2. Together with
`limsup_lintegral_le_of_dominant` — the generalized (Vitali) form of dominated
convergence, in which the dominants are allowed to move — this justifies the
paper's step for every `f` lying in `H^{α/2}` of the enlarged ball.

That hypothesis is exactly the conclusion of Theorem 1.1, so this is an a priori
estimate rather than a proof of the theorem; see the README for why the natural
routes to removing it are circular.
-/

open MeasureTheory Filter Set Metric
open scoped ENNReal NNReal Topology

namespace QFS

variable {d : ℕ}

/-! ## The tile-averaging operator -/

/-- The average of `Φ` over the tile of the `h`-tiling containing `s`.

This is the conditional expectation of `Φ` onto the σ-algebra generated by the
tiling; the two properties that matter are `lintegral_tileAvg` (it preserves the
integral) and its almost-everywhere convergence to `Φ`, which is Lemma 7.2. -/
noncomputable def tileAvg (d : ℕ) (h : ℝ) (Φ : EuclideanSpace ℝ (Fin d) → ℝ≥0∞)
    (s : EuclideanSpace ℝ (Fin d)) : ℝ≥0∞ :=
  (ENNReal.ofReal (h ^ d))⁻¹ * ∫⁻ u in halfClosedCube h (stepIndex d h s), Φ u

/-- **Tile-averaging preserves the integral.** This is what makes `tileAvg Φ` a
usable dominant: the sequence of dominants has *constant* integral, so the
convergence `∫ G_h → ∫ G` required by the generalized dominated convergence
theorem is immediate. -/
theorem lintegral_tileAvg {h : ℝ} (hh : 0 < h) (Φ : EuclideanSpace ℝ (Fin d) → ℝ≥0∞) :
    ∫⁻ s, tileAvg d h Φ s = ∫⁻ s, Φ s := by
  have hpos : (0 : ℝ) < h ^ d := pow_pos hh d
  have hne0 : ENNReal.ofReal (h ^ d) ≠ 0 := by
    simp only [ne_eq, ENNReal.ofReal_eq_zero, not_le]
    exact hpos
  have hnetop : ENNReal.ofReal (h ^ d) ≠ ∞ := ENNReal.ofReal_ne_top
  rw [show (fun s => tileAvg d h Φ s)
      = fun s => (fun x => (ENNReal.ofReal (h ^ d))⁻¹ * ∫⁻ u in halfClosedCube h x, Φ u)
        (stepIndex d h s) from rfl,
    lintegral_stepFun (d := d) hh
      (fun x => (ENNReal.ofReal (h ^ d))⁻¹ * ∫⁻ u in halfClosedCube h x, Φ u),
    lintegral_eq_tsum_halfClosedCube hh]
  refine tsum_congr fun n => ?_
  rw [mul_comm, ← mul_assoc, ENNReal.mul_inv_cancel hne0 hnetop, one_mul]

/-! ## Dominated convergence with a moving dominant -/

/-- **The generalized (Vitali) dominated convergence theorem**, in the one-sided
form Section 3.2 needs: the dominants `G n` may vary with `n`, provided their
integrals do not.

This is what repairs the paper's appeal to dominated convergence: no single
dominant for the family `g_h` is available, but `tileAvg h Φ` is a dominant for
each `h` and, by `lintegral_tileAvg`, all of them have the same integral. -/
theorem limsup_lintegral_le_of_dominant {X : Type*} [MeasurableSpace X] {μ : Measure X}
    {g G : ℕ → X → ℝ≥0∞} {gl Gl : X → ℝ≥0∞}
    (hgm : ∀ n, Measurable (g n)) (hGm : ∀ n, Measurable (G n)) (hglm : Measurable gl)
    (hGlm : Measurable Gl)
    (hle : ∀ n, g n ≤ G n)
    (hgt : ∀ᵐ a ∂μ, Tendsto (fun n => g n a) atTop (𝓝 (gl a)))
    (hGt : ∀ᵐ a ∂μ, Tendsto (fun n => G n a) atTop (𝓝 (Gl a)))
    (hGeq : ∀ n, ∫⁻ a, G n a ∂μ = ∫⁻ a, Gl a ∂μ)
    (hfin : ∫⁻ a, Gl a ∂μ ≠ ∞) :
    limsup (fun n => ∫⁻ a, g n a ∂μ) atTop ≤ ∫⁻ a, gl a ∂μ := by
  set K := ∫⁻ a, Gl a ∂μ with hK
  -- `gl ≤ Gl` almost everywhere, being a limit of the inequalities `g n ≤ G n`
  have hglle : gl ≤ᵐ[μ] Gl := by
    filter_upwards [hgt, hGt] with a ha hb
    exact le_of_tendsto_of_tendsto' ha hb (fun n => hle n a)
  have hgnK : ∀ n, ∫⁻ a, g n a ∂μ ≤ K := fun n => by
    rw [← hGeq n]; exact lintegral_mono (hle n)
  have hglK : ∫⁻ a, gl a ∂μ ≤ K := lintegral_mono_ae hglle
  -- the integrals of the differences
  have hDn : ∀ n, ∫⁻ a, G n a - g n a ∂μ = K - ∫⁻ a, g n a ∂μ := fun n => by
    rw [lintegral_sub (hgm n) (ne_top_of_le_ne_top hfin (hgnK n))
      (Filter.Eventually.of_forall (hle n)), hGeq n]
  have hDl : ∫⁻ a, Gl a - gl a ∂μ = K - ∫⁻ a, gl a ∂μ :=
    lintegral_sub hglm (ne_top_of_le_ne_top hfin hglK) hglle
  -- Fatou for the differences
  have hfatou : ∫⁻ a, liminf (fun n => G n a - g n a) atTop ∂μ
      ≤ liminf (fun n => ∫⁻ a, G n a - g n a ∂μ) atTop :=
    lintegral_liminf_le (fun n => (hGm n).sub (hgm n))
  -- almost everywhere the liminf is the difference of the limits
  have hlim : ∀ᵐ a ∂μ, liminf (fun n => G n a - g n a) atTop = Gl a - gl a := by
    filter_upwards [hgt, hGt, ae_lt_top hGlm hfin] with a ha hb hc
    exact (ENNReal.Tendsto.sub hb ha (Or.inl hc.ne)).liminf_eq
  rw [lintegral_congr_ae hlim, hDl] at hfatou
  simp only [hDn] at hfatou
  rw [ENNReal.liminf_const_sub _ _ hfin] at hfatou
  -- undo the subtraction
  have hlsK : limsup (fun n => ∫⁻ a, g n a ∂μ) atTop ≤ K :=
    limsup_le_of_le (by isBoundedDefault) (Filter.Eventually.of_forall hgnK)
  calc limsup (fun n => ∫⁻ a, g n a ∂μ) atTop
      = K - (K - limsup (fun n => ∫⁻ a, g n a ∂μ) atTop) :=
        (ENNReal.sub_sub_cancel hfin hlsK).symm
    _ ≤ K - (K - ∫⁻ a, gl a ∂μ) := tsub_le_tsub_left hfatou K
    _ = ∫⁻ a, gl a ∂μ := ENNReal.sub_sub_cancel hfin hglK

/-! ## Why the Lipschitz reduction is circular

The natural way to supply the a priori hypothesis is to mollify: `f_ε = f * ρ_ε`
is smooth, hence Lipschitz on a ball, hence in `H^{α/2}`, so the dominated
convergence step above applies to it. What the reduction then needs is that
mollification does not inflate the right-hand side, `|f_ε|_{H_k(B*)} ≲
|f|_{H_k(B**)}`.

That is *not* false — but it is not available either, because `k` is neither
translation invariant nor bounded below off the cone set `E`, and the only route
to it runs through Theorem 1.1 itself. The theorem below makes the circularity
precise: **granted Theorem 1.1, any approximation bounded on `H^{α/2}` is
automatically bounded on `H_k`.** So the hypothesis the reduction would need is a
consequence of the statement it is meant to prove. -/

/-- Granted Theorem 1.1 in its enlarged-ball form, an approximation that is
bounded on `H^{α/2}` — which is what mollification supplies — is bounded on
`H_k` as well. The deduction runs `H_k ≤ Λ·H^{α/2}` (the reverse inequality of
(1.5)), then the hypothesis, then Theorem 1.1; the last step is the circularity.

Consequently the Lipschitz/mollification reduction cannot be used to *prove*
Theorem 1.1: the bound on the mollified right-hand side that it requires is
equivalent to the theorem, not weaker than it. -/
theorem form_le_of_theoremOneOneBall (h11 : TheoremOneOneBall d)
    {ϑ Λ α : ℝ} (hϑ : 0 < ϑ) (hΛ : 1 ≤ Λ) (hα : 0 < α) (hα2 : α < 2) :
    ∃ κ c : ℝ, 1 ≤ κ ∧ 1 ≤ c ∧
      ∀ Γ : Configuration (EuclideanSpace ℝ (Fin d)), IsAdmissible Γ ϑ →
      ∀ k, KernelBounds Γ α Λ k →
      ∀ (x₀ : EuclideanSpace ℝ (Fin d)) (R : ℝ), 0 < R →
      ∀ (u v : EuclideanSpace ℝ (Fin d) → ℝ) (C : ℝ), 0 ≤ C →
        MemLp v 2 (volume.restrict (ball x₀ (κ * R))) →
        formHs (ball x₀ R) α u ≤ ENNReal.ofReal C * formHs (ball x₀ R) α v →
        form (ball x₀ R) k u ≤ ENNReal.ofReal (Λ * C * c) * form (ball x₀ (κ * R)) k v := by
  obtain ⟨κ, c, hκ, hc, H⟩ := h11 ϑ Λ α hϑ hΛ hα hα2
  refine ⟨κ, c, hκ, hc, ?_⟩
  intro Γ hΓ k hk x₀ R hR u v C hC hv hbd
  have h2 := H Γ hΓ k hk x₀ R hR v hv
  calc form (ball x₀ R) k u
      ≤ ENNReal.ofReal Λ * formHs (ball x₀ R) α u := form_le_formHs hk _ _
    _ ≤ ENNReal.ofReal Λ * (ENNReal.ofReal C * formHs (ball x₀ R) α v) := by gcongr
    _ ≤ ENNReal.ofReal Λ *
          (ENNReal.ofReal C * (ENNReal.ofReal c * form (ball x₀ (κ * R)) k v)) := by gcongr
    _ = ENNReal.ofReal (Λ * C * c) * form (ball x₀ (κ * R)) k v := by
        rw [ENNReal.ofReal_mul (mul_nonneg (by linarith) hC), ENNReal.ofReal_mul (by linarith)]
        ring

/-! ## Lipschitz functions satisfy the a priori hypothesis

This is the half of the Lipschitz reduction that does work: a Lipschitz function
lies in `H^{α/2}` of a ball whenever `α < 2`, because
`(f(s) − f(t))²|s − t|^{-d-α} ≤ L²|s − t|^{2-d-α}` and the exponent `2 − d − α`
exceeds `−d`. So mollification does supply the a priori hypothesis of the
dominated-convergence step above; what it does not supply is the bound on the
right-hand side, for the reason recorded in `form_le_of_theoremOneOneBall`. -/

/-- `‖u‖^γ` is integrable on a ball as soon as `γ > −d`; in polar coordinates
this is the integrability of `y^{d-1+γ}` at the origin. -/
theorem lintegral_ball_rpow_lt_top (hd : 0 < d) {r γ : ℝ} (hr : 0 < r)
    (hγ : -(d : ℝ) < γ) :
    ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) r, ENNReal.ofReal (‖u‖ ^ γ) < ∞ := by
  have hdim : Module.finrank ℝ (EuclideanSpace ℝ (Fin d)) = d := by simp
  have hnt : Nontrivial (EuclideanSpace ℝ (Fin d)) := by
    rw [← Module.finrank_pos_iff (R := ℝ), hdim]; exact hd
  -- the radial integrand, after the polar-coordinates reduction
  have hexp : (-1 : ℝ) < ((d - 1 : ℕ) : ℝ) + γ := by
    have : ((d - 1 : ℕ) : ℝ) = (d : ℝ) - 1 := by
      have : 1 ≤ d := hd
      push_cast [Nat.cast_sub this]
      ring
    rw [this]; linarith
  have hrad : IntegrableOn
      (fun y : ℝ => y ^ (Module.finrank ℝ (EuclideanSpace ℝ (Fin d)) - 1) • y ^ γ)
      (Ioo 0 r) volume := by
    rw [hdim]
    refine (integrableOn_congr_fun ?_ measurableSet_Ioo).mpr
      ((intervalIntegral.integrableOn_Ioo_rpow_iff hr).mpr hexp)
    intro y hy
    have hy0 : (0 : ℝ) < y := hy.1
    change y ^ (d - 1) • y ^ γ = y ^ (((d - 1 : ℕ) : ℝ) + γ)
    rw [smul_eq_mul, ← Real.rpow_natCast y (d - 1), ← Real.rpow_add hy0]
  have hint : IntegrableOn (fun u : EuclideanSpace ℝ (Fin d) => ‖u‖ ^ γ) (ball 0 r) volume :=
    (integrableOn_fun_norm_addHaar volume (f := fun y : ℝ => y ^ γ) (r := r)).mpr hrad
  have := hint.hasFiniteIntegral
  refine lt_of_le_of_lt (le_of_eq ?_) this
  refine lintegral_congr_ae ?_
  filter_upwards with u
  rw [← ofReal_norm, Real.norm_eq_abs, abs_of_nonneg (Real.rpow_nonneg (norm_nonneg u) γ)]


/-- **A Lipschitz function lies in `H^{α/2}` of a ball, for every `α < 2`.**

This is what the mollification step of the Lipschitz reduction delivers: it puts
`f_ε` into the class where `limsup_lintegral_le_of_dominant` applies. -/
theorem formHs_lt_top_of_lipschitzOn (hd : 0 < d) {α : ℝ} (hα2 : α < 2)
    {x₀ : EuclideanSpace ℝ (Fin d)} {R : ℝ} (hR : 0 < R)
    {f : EuclideanSpace ℝ (Fin d) → ℝ} {L : ℝ≥0}
    (hf : LipschitzOnWith L f (ball x₀ R)) :
    formHs (ball x₀ R) α f < ∞ := by
  set γ : ℝ := 2 - (d : ℝ) - α with hγdef
  have hγ : -(d : ℝ) < γ := by rw [hγdef]; linarith
  set G : EuclideanSpace ℝ (Fin d) → ℝ≥0∞ := fun u => ENNReal.ofReal (‖u‖ ^ γ) with hGdef
  have hGmeas : Measurable G := by rw [hGdef]; fun_prop
  -- the pointwise majorant
  have hmaj : ∀ p ∈ ball x₀ R ×ˢ ball x₀ R,
      ENNReal.ofReal ((f p.2 - f p.1) ^ 2) * jumpKernel d α p.1 p.2
        ≤ ENNReal.ofReal ((L : ℝ) ^ 2) * G (p.1 - p.2) := by
    rintro ⟨s, t⟩ ⟨hs, ht⟩
    rcases eq_or_ne s t with rfl | hst
    · simp
    have hn : 0 < ‖s - t‖ := by
      rw [norm_pos_iff]; exact sub_ne_zero_of_ne hst
    have hlip : |f t - f s| ≤ (L : ℝ) * ‖s - t‖ := by
      have := hf.dist_le_mul t ht s hs
      rwa [Real.dist_eq, dist_eq_norm, norm_sub_rev t s] at this
    have hsq : (f t - f s) ^ 2 ≤ (L : ℝ) ^ 2 * ‖s - t‖ ^ 2 := by
      nlinarith [sq_abs (f t - f s), abs_nonneg (f t - f s), norm_nonneg (s - t),
        NNReal.coe_nonneg L]
    have hker : jumpKernel d α s t = ENNReal.ofReal (‖s - t‖ ^ (-(d : ℝ) - α)) := rfl
    have hcomb : ‖s - t‖ ^ 2 * ‖s - t‖ ^ (-(d : ℝ) - α) = ‖s - t‖ ^ γ := by
      rw [← Real.rpow_natCast ‖s - t‖ 2, ← Real.rpow_add hn, hγdef]
      congr 1
      push_cast
      ring
    rw [hker, hGdef, ← ENNReal.ofReal_mul (by positivity), ← ENNReal.ofReal_mul (by positivity)]
    refine ENNReal.ofReal_le_ofReal ?_
    calc (f t - f s) ^ 2 * ‖s - t‖ ^ (-(d : ℝ) - α)
        ≤ ((L : ℝ) ^ 2 * ‖s - t‖ ^ 2) * ‖s - t‖ ^ (-(d : ℝ) - α) := by
          exact mul_le_mul_of_nonneg_right hsq (Real.rpow_nonneg (norm_nonneg _) _)
      _ = (L : ℝ) ^ 2 * ‖s - t‖ ^ γ := by rw [mul_assoc, hcomb]
  -- the majorant has finite integral
  have hprodmeas : Measurable fun p : EuclideanSpace ℝ (Fin d) × EuclideanSpace ℝ (Fin d) =>
      ENNReal.ofReal ((L : ℝ) ^ 2) * G (p.1 - p.2) :=
    (hGmeas.comp (measurable_fst.sub measurable_snd)).const_mul _
  have hinner : ∀ s : EuclideanSpace ℝ (Fin d), s ∈ ball x₀ R →
      ∫⁻ t in ball x₀ R, G (s - t)
        ≤ ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G u := by
    intro s hs
    have hsub : ball x₀ R ⊆ (fun t => t - s) ⁻¹' ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R) := by
      intro t ht
      simp only [Set.mem_preimage, mem_ball, dist_zero_right]
      have h1 : ‖t - x₀‖ < R := by rwa [mem_ball, dist_eq_norm] at ht
      have h2 : ‖s - x₀‖ < R := by rwa [mem_ball, dist_eq_norm] at hs
      calc ‖t - s‖ = ‖(t - x₀) - (s - x₀)‖ := by rw [sub_sub_sub_cancel_right]
        _ ≤ ‖t - x₀‖ + ‖s - x₀‖ := norm_sub_le _ _
        _ < 2 * R := by linarith
    calc ∫⁻ t in ball x₀ R, G (s - t)
        = ∫⁻ t in ball x₀ R, G (t - s) := by
          refine lintegral_congr fun t => ?_
          rw [hGdef]
          simp only [norm_sub_rev]
      _ ≤ ∫⁻ t in (fun t => t - s) ⁻¹' ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G (t - s) :=
          lintegral_mono_set hsub
      _ = ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G u :=
          (measurePreserving_sub_right volume s).setLIntegral_comp_preimage
            measurableSet_ball hGmeas
  have hfin : ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G u < ∞ :=
    lintegral_ball_rpow_lt_top hd (by linarith) hγ
  calc formHs (ball x₀ R) α f
      ≤ ∫⁻ p in ball x₀ R ×ˢ ball x₀ R, ENNReal.ofReal ((L : ℝ) ^ 2) * G (p.1 - p.2) := by
        refine lintegral_mono_ae ?_
        filter_upwards [ae_restrict_mem ((measurableSet_ball).prod measurableSet_ball)]
          with p hp using hmaj p hp
    _ = ENNReal.ofReal ((L : ℝ) ^ 2) *
          ∫⁻ p in ball x₀ R ×ˢ ball x₀ R, G (p.1 - p.2) :=
        lintegral_const_mul' _ _ ENNReal.ofReal_ne_top
    _ = ENNReal.ofReal ((L : ℝ) ^ 2) *
          ∫⁻ s in ball x₀ R, ∫⁻ t in ball x₀ R, G (s - t) := by
        rw [Measure.volume_eq_prod, ← Measure.prod_restrict,
          lintegral_prod
            (fun p : EuclideanSpace ℝ (Fin d) × EuclideanSpace ℝ (Fin d) => G (p.1 - p.2))
            (hGmeas.comp (measurable_fst.sub measurable_snd)).aemeasurable]
    _ ≤ ENNReal.ofReal ((L : ℝ) ^ 2) *
          ∫⁻ _ in ball x₀ R, ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G u := by
        refine mul_le_mul' le_rfl (lintegral_mono_ae ?_)
        filter_upwards [ae_restrict_mem measurableSet_ball] with s hs using hinner s hs
    _ < ∞ := by
        rw [setLIntegral_const]
        exact ENNReal.mul_lt_top ENNReal.ofReal_lt_top
          (ENNReal.mul_lt_top hfin measure_ball_lt_top)

end QFS
