import QuadraticFormsSobolev.LebesgueDiff
import QuadraticFormsSobolev.Section1

/-!
# The limit procedure of Section 3.2

Section 3.2 passes from the discrete inequality `(discret)` to the continuous
one by letting `h → 0`. On the left it uses Fatou. On the right it asserts

> For the right hand side in (discret) this implies with help of dominated
> convergence … `∫ g_h → ∫ g`

without exhibiting a dominating function, and none is available unconditionally
(see the README).

This file supplies the missing ingredient in the form the argument can use. The
point is that a *varying* dominant suffices, and that the tile-averaging
operator `tileAvg` provides one: it is an averaging (conditional expectation)
operator, so it **preserves the integral exactly** (`lintegral_tileAvg`), and it
converges almost everywhere by Lemma 7.2. Together with
`limsup_lintegral_le_of_dominant` — the generalized (Vitali) form of dominated
convergence, in which the dominants are allowed to move — this justifies the
paper's step for every `f` lying in `H^{α/2}` of the enlarged ball.

That hypothesis is exactly the conclusion of Theorem 1.1, so this is an a priori
estimate rather than a proof of the theorem; see the README for why the natural
routes to removing it are circular.
-/

open MeasureTheory Filter Set Metric
open scoped ENNReal NNReal Topology

namespace QFS

variable {d : ℕ}

/-! ## The tile-averaging operator -/

/-- The average of `Φ` over the tile of the `h`-tiling containing `s`.

This is the conditional expectation of `Φ` onto the σ-algebra generated by the
tiling; the two properties that matter are `lintegral_tileAvg` (it preserves the
integral) and its almost-everywhere convergence to `Φ`, which is Lemma 7.2. -/
noncomputable def tileAvg (d : ℕ) (h : ℝ) (Φ : EuclideanSpace ℝ (Fin d) → ℝ≥0∞)
    (s : EuclideanSpace ℝ (Fin d)) : ℝ≥0∞ :=
  (ENNReal.ofReal (h ^ d))⁻¹ * ∫⁻ u in halfClosedCube h (stepIndex d h s), Φ u

/-- **Tile-averaging preserves the integral.** This is what makes `tileAvg Φ` a
usable dominant: the sequence of dominants has *constant* integral, so the
convergence `∫ G_h → ∫ G` required by the generalized dominated convergence
theorem is immediate. -/
theorem lintegral_tileAvg {h : ℝ} (hh : 0 < h) (Φ : EuclideanSpace ℝ (Fin d) → ℝ≥0∞) :
    ∫⁻ s, tileAvg d h Φ s = ∫⁻ s, Φ s := by
  have hpos : (0 : ℝ) < h ^ d := pow_pos hh d
  have hne0 : ENNReal.ofReal (h ^ d) ≠ 0 := by
    simp only [ne_eq, ENNReal.ofReal_eq_zero, not_le]
    exact hpos
  have hnetop : ENNReal.ofReal (h ^ d) ≠ ∞ := ENNReal.ofReal_ne_top
  rw [show (fun s => tileAvg d h Φ s)
      = fun s => (fun x => (ENNReal.ofReal (h ^ d))⁻¹ * ∫⁻ u in halfClosedCube h x, Φ u)
        (stepIndex d h s) from rfl,
    lintegral_stepFun (d := d) hh
      (fun x => (ENNReal.ofReal (h ^ d))⁻¹ * ∫⁻ u in halfClosedCube h x, Φ u),
    lintegral_eq_tsum_halfClosedCube hh]
  refine tsum_congr fun n => ?_
  rw [mul_comm, ← mul_assoc, ENNReal.mul_inv_cancel hne0 hnetop, one_mul]

/-! ## Dominated convergence with a moving dominant -/

/-- **The generalized (Vitali) dominated convergence theorem**, in the one-sided
form Section 3.2 needs: the dominants `G n` may vary with `n`, provided their
integrals do not.

This is what repairs the paper's appeal to dominated convergence: no single
dominant for the family `g_h` is available, but `tileAvg h Φ` is a dominant for
each `h` and, by `lintegral_tileAvg`, all of them have the same integral. -/
theorem limsup_lintegral_le_of_dominant {X : Type*} [MeasurableSpace X] {μ : Measure X}
    {g G : ℕ → X → ℝ≥0∞} {gl Gl : X → ℝ≥0∞}
    (hgm : ∀ n, Measurable (g n)) (hGm : ∀ n, Measurable (G n)) (hglm : Measurable gl)
    (hGlm : Measurable Gl)
    (hle : ∀ n, g n ≤ G n)
    (hgt : ∀ᵐ a ∂μ, Tendsto (fun n => g n a) atTop (𝓝 (gl a)))
    (hGt : ∀ᵐ a ∂μ, Tendsto (fun n => G n a) atTop (𝓝 (Gl a)))
    (hGeq : ∀ n, ∫⁻ a, G n a ∂μ = ∫⁻ a, Gl a ∂μ)
    (hfin : ∫⁻ a, Gl a ∂μ ≠ ∞) :
    limsup (fun n => ∫⁻ a, g n a ∂μ) atTop ≤ ∫⁻ a, gl a ∂μ := by
  set K := ∫⁻ a, Gl a ∂μ with hK
  -- `gl ≤ Gl` almost everywhere, being a limit of the inequalities `g n ≤ G n`
  have hglle : gl ≤ᵐ[μ] Gl := by
    filter_upwards [hgt, hGt] with a ha hb
    exact le_of_tendsto_of_tendsto' ha hb (fun n => hle n a)
  have hgnK : ∀ n, ∫⁻ a, g n a ∂μ ≤ K := fun n => by
    rw [← hGeq n]; exact lintegral_mono (hle n)
  have hglK : ∫⁻ a, gl a ∂μ ≤ K := lintegral_mono_ae hglle
  -- the integrals of the differences
  have hDn : ∀ n, ∫⁻ a, G n a - g n a ∂μ = K - ∫⁻ a, g n a ∂μ := fun n => by
    rw [lintegral_sub (hgm n) (ne_top_of_le_ne_top hfin (hgnK n))
      (Filter.Eventually.of_forall (hle n)), hGeq n]
  have hDl : ∫⁻ a, Gl a - gl a ∂μ = K - ∫⁻ a, gl a ∂μ :=
    lintegral_sub hglm (ne_top_of_le_ne_top hfin hglK) hglle
  -- Fatou for the differences
  have hfatou : ∫⁻ a, liminf (fun n => G n a - g n a) atTop ∂μ
      ≤ liminf (fun n => ∫⁻ a, G n a - g n a ∂μ) atTop :=
    lintegral_liminf_le (fun n => (hGm n).sub (hgm n))
  -- almost everywhere the liminf is the difference of the limits
  have hlim : ∀ᵐ a ∂μ, liminf (fun n => G n a - g n a) atTop = Gl a - gl a := by
    filter_upwards [hgt, hGt, ae_lt_top hGlm hfin] with a ha hb hc
    exact (ENNReal.Tendsto.sub hb ha (Or.inl hc.ne)).liminf_eq
  rw [lintegral_congr_ae hlim, hDl] at hfatou
  simp only [hDn] at hfatou
  rw [ENNReal.liminf_const_sub _ _ hfin] at hfatou
  -- undo the subtraction
  have hlsK : limsup (fun n => ∫⁻ a, g n a ∂μ) atTop ≤ K :=
    limsup_le_of_le (by isBoundedDefault) (Filter.Eventually.of_forall hgnK)
  calc limsup (fun n => ∫⁻ a, g n a ∂μ) atTop
      = K - (K - limsup (fun n => ∫⁻ a, g n a ∂μ) atTop) :=
        (ENNReal.sub_sub_cancel hfin hlsK).symm
    _ ≤ K - (K - ∫⁻ a, gl a ∂μ) := tsub_le_tsub_left hfatou K
    _ = ∫⁻ a, gl a ∂μ := ENNReal.sub_sub_cancel hfin hglK

/-! ## Why the Lipschitz reduction is circular

The natural way to supply the a priori hypothesis is to mollify: `f_ε = f * ρ_ε`
is smooth, hence Lipschitz on a ball, hence in `H^{α/2}`, so the dominated
convergence step above applies to it. What the reduction then needs is that
mollification does not inflate the right-hand side, `|f_ε|_{H_k(B*)} ≲
|f|_{H_k(B**)}`.

That is *not* false — but it is not available either, because `k` is neither
translation invariant nor bounded below off the cone set `E`, and the only route
to it runs through Theorem 1.1 itself. The theorem below makes the circularity
precise: **granted Theorem 1.1, any approximation bounded on `H^{α/2}` is
automatically bounded on `H_k`.** So the hypothesis the reduction would need is a
consequence of the statement it is meant to prove. -/

/-- Granted Theorem 1.1 in its enlarged-ball form, an approximation that is
bounded on `H^{α/2}` — which is what mollification supplies — is bounded on
`H_k` as well. The deduction runs `H_k ≤ Λ·H^{α/2}` (the reverse inequality of
(1.5)), then the hypothesis, then Theorem 1.1; the last step is the circularity.

Consequently the Lipschitz/mollification reduction cannot be used to *prove*
Theorem 1.1: the bound on the mollified right-hand side that it requires is
equivalent to the theorem, not weaker than it. -/
theorem form_le_of_theoremOneOneBall (h11 : TheoremOneOneBall d)
    {ϑ Λ α : ℝ} (hϑ : 0 < ϑ) (hΛ : 1 ≤ Λ) (hα : 0 < α) (hα2 : α < 2) :
    ∃ κ c : ℝ, 1 ≤ κ ∧ 1 ≤ c ∧
      ∀ Γ : Configuration (EuclideanSpace ℝ (Fin d)), IsAdmissible Γ ϑ →
      ∀ k, KernelBounds Γ α Λ k →
      ∀ (x₀ : EuclideanSpace ℝ (Fin d)) (R : ℝ), 0 < R →
      ∀ (u v : EuclideanSpace ℝ (Fin d) → ℝ) (C : ℝ), 0 ≤ C →
        MemLp v 2 (volume.restrict (ball x₀ (κ * R))) →
        formHs (ball x₀ R) α u ≤ ENNReal.ofReal C * formHs (ball x₀ R) α v →
        form (ball x₀ R) k u ≤ ENNReal.ofReal (Λ * C * c) * form (ball x₀ (κ * R)) k v := by
  obtain ⟨κ, c, hκ, hc, H⟩ := h11 ϑ Λ α hϑ hΛ hα hα2
  refine ⟨κ, c, hκ, hc, ?_⟩
  intro Γ hΓ k hk x₀ R hR u v C hC hv hbd
  have h2 := H Γ hΓ k hk x₀ R hR v hv
  calc form (ball x₀ R) k u
      ≤ ENNReal.ofReal Λ * formHs (ball x₀ R) α u := form_le_formHs hk _ _
    _ ≤ ENNReal.ofReal Λ * (ENNReal.ofReal C * formHs (ball x₀ R) α v) := by gcongr
    _ ≤ ENNReal.ofReal Λ *
          (ENNReal.ofReal C * (ENNReal.ofReal c * form (ball x₀ (κ * R)) k v)) := by gcongr
    _ = ENNReal.ofReal (Λ * C * c) * form (ball x₀ (κ * R)) k v := by
        rw [ENNReal.ofReal_mul (mul_nonneg (by linarith) hC), ENNReal.ofReal_mul (by linarith)]
        ring

/-! ## Lipschitz functions satisfy the a priori hypothesis

This is the half of the Lipschitz reduction that does work: a Lipschitz function
lies in `H^{α/2}` of a ball whenever `α < 2`, because
`(f(s) − f(t))²|s − t|^{-d-α} ≤ L²|s − t|^{2-d-α}` and the exponent `2 − d − α`
exceeds `−d`. So mollification does supply the a priori hypothesis of the
dominated-convergence step above; what it does not supply is the bound on the
right-hand side, for the reason recorded in `form_le_of_theoremOneOneBall`. -/

/-- `‖u‖^γ` is integrable on a ball as soon as `γ > −d`; in polar coordinates
this is the integrability of `y^{d-1+γ}` at the origin. -/
theorem lintegral_ball_rpow_lt_top (hd : 0 < d) {r γ : ℝ} (hr : 0 < r)
    (hγ : -(d : ℝ) < γ) :
    ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) r, ENNReal.ofReal (‖u‖ ^ γ) < ∞ := by
  have hdim : Module.finrank ℝ (EuclideanSpace ℝ (Fin d)) = d := by simp
  have hnt : Nontrivial (EuclideanSpace ℝ (Fin d)) := by
    rw [← Module.finrank_pos_iff (R := ℝ), hdim]; exact hd
  -- the radial integrand, after the polar-coordinates reduction
  have hexp : (-1 : ℝ) < ((d - 1 : ℕ) : ℝ) + γ := by
    have : ((d - 1 : ℕ) : ℝ) = (d : ℝ) - 1 := by
      have : 1 ≤ d := hd
      push_cast [Nat.cast_sub this]
      ring
    rw [this]; linarith
  have hrad : IntegrableOn
      (fun y : ℝ => y ^ (Module.finrank ℝ (EuclideanSpace ℝ (Fin d)) - 1) • y ^ γ)
      (Ioo 0 r) volume := by
    rw [hdim]
    refine (integrableOn_congr_fun ?_ measurableSet_Ioo).mpr
      ((intervalIntegral.integrableOn_Ioo_rpow_iff hr).mpr hexp)
    intro y hy
    have hy0 : (0 : ℝ) < y := hy.1
    change y ^ (d - 1) • y ^ γ = y ^ (((d - 1 : ℕ) : ℝ) + γ)
    rw [smul_eq_mul, ← Real.rpow_natCast y (d - 1), ← Real.rpow_add hy0]
  have hint : IntegrableOn (fun u : EuclideanSpace ℝ (Fin d) => ‖u‖ ^ γ) (ball 0 r) volume :=
    (integrableOn_fun_norm_addHaar volume (f := fun y : ℝ => y ^ γ) (r := r)).mpr hrad
  have := hint.hasFiniteIntegral
  refine lt_of_le_of_lt (le_of_eq ?_) this
  refine lintegral_congr_ae ?_
  filter_upwards with u
  rw [← ofReal_norm, Real.norm_eq_abs, abs_of_nonneg (Real.rpow_nonneg (norm_nonneg u) γ)]


/-- **A Lipschitz function lies in `H^{α/2}` of a ball, for every `α < 2`.**

This is what the mollification step of the Lipschitz reduction delivers: it puts
`f_ε` into the class where `limsup_lintegral_le_of_dominant` applies. -/
theorem formHs_lt_top_of_lipschitzOn (hd : 0 < d) {α : ℝ} (hα2 : α < 2)
    {x₀ : EuclideanSpace ℝ (Fin d)} {R : ℝ} (hR : 0 < R)
    {f : EuclideanSpace ℝ (Fin d) → ℝ} {L : ℝ≥0}
    (hf : LipschitzOnWith L f (ball x₀ R)) :
    formHs (ball x₀ R) α f < ∞ := by
  set γ : ℝ := 2 - (d : ℝ) - α with hγdef
  have hγ : -(d : ℝ) < γ := by rw [hγdef]; linarith
  set G : EuclideanSpace ℝ (Fin d) → ℝ≥0∞ := fun u => ENNReal.ofReal (‖u‖ ^ γ) with hGdef
  have hGmeas : Measurable G := by rw [hGdef]; fun_prop
  -- the pointwise majorant
  have hmaj : ∀ p ∈ ball x₀ R ×ˢ ball x₀ R,
      ENNReal.ofReal ((f p.2 - f p.1) ^ 2) * jumpKernel d α p.1 p.2
        ≤ ENNReal.ofReal ((L : ℝ) ^ 2) * G (p.1 - p.2) := by
    rintro ⟨s, t⟩ ⟨hs, ht⟩
    rcases eq_or_ne s t with rfl | hst
    · simp
    have hn : 0 < ‖s - t‖ := by
      rw [norm_pos_iff]; exact sub_ne_zero_of_ne hst
    have hlip : |f t - f s| ≤ (L : ℝ) * ‖s - t‖ := by
      have := hf.dist_le_mul t ht s hs
      rwa [Real.dist_eq, dist_eq_norm, norm_sub_rev t s] at this
    have hsq : (f t - f s) ^ 2 ≤ (L : ℝ) ^ 2 * ‖s - t‖ ^ 2 := by
      nlinarith [sq_abs (f t - f s), abs_nonneg (f t - f s), norm_nonneg (s - t),
        NNReal.coe_nonneg L]
    have hker : jumpKernel d α s t = ENNReal.ofReal (‖s - t‖ ^ (-(d : ℝ) - α)) := rfl
    have hcomb : ‖s - t‖ ^ 2 * ‖s - t‖ ^ (-(d : ℝ) - α) = ‖s - t‖ ^ γ := by
      rw [← Real.rpow_natCast ‖s - t‖ 2, ← Real.rpow_add hn, hγdef]
      congr 1
      push_cast
      ring
    rw [hker, hGdef, ← ENNReal.ofReal_mul (by positivity), ← ENNReal.ofReal_mul (by positivity)]
    refine ENNReal.ofReal_le_ofReal ?_
    calc (f t - f s) ^ 2 * ‖s - t‖ ^ (-(d : ℝ) - α)
        ≤ ((L : ℝ) ^ 2 * ‖s - t‖ ^ 2) * ‖s - t‖ ^ (-(d : ℝ) - α) := by
          exact mul_le_mul_of_nonneg_right hsq (Real.rpow_nonneg (norm_nonneg _) _)
      _ = (L : ℝ) ^ 2 * ‖s - t‖ ^ γ := by rw [mul_assoc, hcomb]
  -- the majorant has finite integral
  have hprodmeas : Measurable fun p : EuclideanSpace ℝ (Fin d) × EuclideanSpace ℝ (Fin d) =>
      ENNReal.ofReal ((L : ℝ) ^ 2) * G (p.1 - p.2) :=
    (hGmeas.comp (measurable_fst.sub measurable_snd)).const_mul _
  have hinner : ∀ s : EuclideanSpace ℝ (Fin d), s ∈ ball x₀ R →
      ∫⁻ t in ball x₀ R, G (s - t)
        ≤ ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G u := by
    intro s hs
    have hsub : ball x₀ R ⊆ (fun t => t - s) ⁻¹' ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R) := by
      intro t ht
      simp only [Set.mem_preimage, mem_ball, dist_zero_right]
      have h1 : ‖t - x₀‖ < R := by rwa [mem_ball, dist_eq_norm] at ht
      have h2 : ‖s - x₀‖ < R := by rwa [mem_ball, dist_eq_norm] at hs
      calc ‖t - s‖ = ‖(t - x₀) - (s - x₀)‖ := by rw [sub_sub_sub_cancel_right]
        _ ≤ ‖t - x₀‖ + ‖s - x₀‖ := norm_sub_le _ _
        _ < 2 * R := by linarith
    calc ∫⁻ t in ball x₀ R, G (s - t)
        = ∫⁻ t in ball x₀ R, G (t - s) := by
          refine lintegral_congr fun t => ?_
          rw [hGdef]
          simp only [norm_sub_rev]
      _ ≤ ∫⁻ t in (fun t => t - s) ⁻¹' ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G (t - s) :=
          lintegral_mono_set hsub
      _ = ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G u :=
          (measurePreserving_sub_right volume s).setLIntegral_comp_preimage
            measurableSet_ball hGmeas
  have hfin : ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G u < ∞ :=
    lintegral_ball_rpow_lt_top hd (by linarith) hγ
  calc formHs (ball x₀ R) α f
      ≤ ∫⁻ p in ball x₀ R ×ˢ ball x₀ R, ENNReal.ofReal ((L : ℝ) ^ 2) * G (p.1 - p.2) := by
        refine lintegral_mono_ae ?_
        filter_upwards [ae_restrict_mem ((measurableSet_ball).prod measurableSet_ball)]
          with p hp using hmaj p hp
    _ = ENNReal.ofReal ((L : ℝ) ^ 2) *
          ∫⁻ p in ball x₀ R ×ˢ ball x₀ R, G (p.1 - p.2) :=
        lintegral_const_mul' _ _ ENNReal.ofReal_ne_top
    _ = ENNReal.ofReal ((L : ℝ) ^ 2) *
          ∫⁻ s in ball x₀ R, ∫⁻ t in ball x₀ R, G (s - t) := by
        rw [Measure.volume_eq_prod, ← Measure.prod_restrict,
          lintegral_prod
            (fun p : EuclideanSpace ℝ (Fin d) × EuclideanSpace ℝ (Fin d) => G (p.1 - p.2))
            (hGmeas.comp (measurable_fst.sub measurable_snd)).aemeasurable]
    _ ≤ ENNReal.ofReal ((L : ℝ) ^ 2) *
          ∫⁻ _ in ball x₀ R, ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) (2 * R), G u := by
        refine mul_le_mul' le_rfl (lintegral_mono_ae ?_)
        filter_upwards [ae_restrict_mem measurableSet_ball] with s hs using hinner s hs
    _ < ∞ := by
        rw [setLIntegral_const]
        exact ENNReal.mul_lt_top ENNReal.ofReal_lt_top
          (ENNReal.mul_lt_top hfin measure_ball_lt_top)

/-! ## Reducing the open statement to a modulus of continuity

The obstruction in §3.2 is the a priori hypothesis `f ∈ H^{α/2}(B*)`. It can be
weakened substantially, and the weakening is worth recording because it replaces
a singular double integral by a quantity with no singularity at all.

Decompose the difference of two cube averages as
`f_h(x) − f_h(y) = (f_h(x) − f(s)) + (f(s) − f(t)) + (f(t) − f_h(y))`, multiply by
`k(s,t)` and integrate over `Ã_h(x) × Ã_h(y)`. Summing over the pairs, the middle
term contributes `|f|²_{H_k(B*)}`, and each outer term contributes
`‖f − E_h f‖²_{L²(B*)}` times `sup_s ∫_{|s−t| > h/2} k(s,t) dt = O(Λ h^{-α})`:

  `∫∫ g_h ≤ 9 |f|²_{H_k(B*)} + C(d,α,Λ) · A_h`,   `A_h := h^{-α}‖f − E_h f‖²_{L²(B*)}`.

Fatou on the left of `(discret)` then gives `|f|_{H^{α/2}(B)} < ∞` as soon as
`liminf_{h→0} A_h < ∞` — no dominated convergence and no limit on the right at
all. So:

> **It suffices that `liminf_{h→0} h^{-α}‖f − E_h f‖²_{L²(B*)} < ∞`.**

`A_h` is an `L²` modulus of continuity at a single scale — a Besov `B^{α/2}_{2,∞}`
quantity, strictly weaker than the `B^{α/2}_{2,2} = H^{α/2}` membership the paper's
argument assumes.

And `A_h` splits into a cone part and an off-cone part, of which **the cone part
is already bounded, uniformly in `h`** — that is `oscillation_same_tile_le_form`
below. The residual is the off-cone oscillation inside single tiles: for `s,t` in
one cube of side `h` with `t ∉ V^Γ[s]`, the difference `f(s) − f(t)` must be
recovered by chaining through cone pairs. That is exactly what §§4–6 do, but in
the discrete setting, where the tiles are points and the within-tile oscillation
is invisible. -/

/-- The set of pairs each of which sees the other's cone: where the lower bound
of (1.4) has force. -/
def coneSet (Γ : Configuration (EuclideanSpace ℝ (Fin d))) :
    Set (EuclideanSpace ℝ (Fin d) × EuclideanSpace ℝ (Fin d)) :=
  {p | p.2 ∈ coneAt Γ p.1 ∨ p.1 ∈ coneAt Γ p.2}

/-- The set of pairs lying in a common tile of the `h`-tiling. -/
def sameTile (d : ℕ) (h : ℝ) :
    Set (EuclideanSpace ℝ (Fin d) × EuclideanSpace ℝ (Fin d)) :=
  {p | stepIndex d h p.1 = stepIndex d h p.2}

lemma norm_sub_le_of_sameTile {h : ℝ} (hh : 0 < h)
    {p : EuclideanSpace ℝ (Fin d) × EuclideanSpace ℝ (Fin d)} (hp : p ∈ sameTile d h) :
    ‖p.1 - p.2‖ ≤ Real.sqrt d * h := by
  have h1 := mem_halfClosedCube_stepIndex hh p.1
  have h2 := mem_halfClosedCube_stepIndex hh p.2
  rw [show stepIndex d h p.2 = stepIndex d h p.1 from hp.symm] at h2
  have hcoord : ∀ i, |(p.1 - p.2) i| ≤ h := by
    intro i
    have a1 := h1 i
    have a2 := h2 i
    rw [Set.mem_Ico] at a1 a2
    have : (p.1 - p.2) i = p.1 i - p.2 i := by simp
    rw [this, abs_le]
    constructor <;> linarith [a1.1, a1.2, a2.1, a2.2]
  exact le_trans (norm_le_sqrt_dim_mul_infNorm _)
    (mul_le_mul_of_nonneg_left (infNorm_le hh.le hcoord) (Real.sqrt_nonneg _))

/-- **The cone-restricted oscillation at scale `r`.** If every pair of `A` is at
distance at most `r` and lies in the cone set, the plain `L²` oscillation over
`A` is at most `Λ r^{d+α}` times the `H_k` energy over `A`.

This is the lower bound of (1.4) used in the one direction that costs nothing:
on a *bounded* set of pairs the singular kernel is bounded **below**, so it
dominates the flat measure. -/
theorem lintegral_sq_le_form_of_close {Γ : Configuration (EuclideanSpace ℝ (Fin d))}
    {α Λ : ℝ} {k : EuclideanSpace ℝ (Fin d) → EuclideanSpace ℝ (Fin d) → ℝ≥0∞}
    (hk : KernelBounds Γ α Λ k) (hα : 0 ≤ α) {r : ℝ} (hr : 0 < r)
    (f : EuclideanSpace ℝ (Fin d) → ℝ)
    {A : Set (EuclideanSpace ℝ (Fin d) × EuclideanSpace ℝ (Fin d))} (hAm : MeasurableSet A)
    (hA : ∀ p ∈ A, ‖p.1 - p.2‖ ≤ r ∧ p ∈ coneSet Γ) :
    ∫⁻ p in A, ENNReal.ofReal ((f p.2 - f p.1) ^ 2)
      ≤ ENNReal.ofReal (Λ * r ^ ((d : ℝ) + α)) *
        ∫⁻ p in A, ENNReal.ofReal ((f p.2 - f p.1) ^ 2) * k p.1 p.2 := by
  have hΛ : (0 : ℝ) < Λ := lt_of_lt_of_le zero_lt_one hk.one_le
  have hexp : (-(d : ℝ) - α) ≤ 0 := by
    have : (0 : ℝ) ≤ (d : ℝ) := Nat.cast_nonneg d
    linarith
  rw [← lintegral_const_mul' _ _ ENNReal.ofReal_ne_top]
  refine lintegral_mono_ae ?_
  filter_upwards [ae_restrict_mem hAm] with p hp
  obtain ⟨hclose, hcone⟩ := hA p hp
  rcases eq_or_ne p.1 p.2 with heq | hne
  · simp [heq]
  have hn : 0 < ‖p.1 - p.2‖ := by rw [norm_pos_iff]; exact sub_ne_zero_of_ne hne
  -- on the cone set the indicators sum to at least one
  have hind : (1 : ℝ≥0∞) ≤ indE (coneAt Γ p.1) p.2 + indE (coneAt Γ p.2) p.1 := by
    rcases hcone with h | h
    · have h1 : indE (coneAt Γ p.1) p.2 = 1 := by simp [indE, Set.indicator_of_mem h]
      rw [h1]; exact le_self_add
    · have h1 : indE (coneAt Γ p.2) p.1 = 1 := by simp [indE, Set.indicator_of_mem h]
      rw [h1]; exact le_add_self
  -- hence the kernel is bounded below by the flat lower bound
  have hklow : ENNReal.ofReal (Λ⁻¹ * ‖p.1 - p.2‖ ^ (-(d : ℝ) - α)) ≤ k p.1 p.2 := by
    have h0 : ENNReal.ofReal (Λ⁻¹ * ‖p.1 - p.2‖ ^ (-(d : ℝ) - α))
        = ENNReal.ofReal Λ⁻¹ * jumpKernel d α p.1 p.2 := by
      rw [ENNReal.ofReal_mul (le_of_lt (inv_pos.mpr hΛ))]; rfl
    rw [h0]
    refine le_trans (mul_le_mul' le_rfl ?_) (hk.lower p.1 p.2)
    calc jumpKernel d α p.1 p.2 = 1 * jumpKernel d α p.1 p.2 := (one_mul _).symm
      _ ≤ (indE (coneAt Γ p.1) p.2 + indE (coneAt Γ p.2) p.1) * jumpKernel d α p.1 p.2 :=
          mul_le_mul' hind le_rfl
  -- and `Λ r^{d+α}` times that lower bound is at least one
  have hgeone : (1 : ℝ≥0∞) ≤ ENNReal.ofReal (Λ * r ^ ((d : ℝ) + α)) *
      ENNReal.ofReal (Λ⁻¹ * ‖p.1 - p.2‖ ^ (-(d : ℝ) - α)) := by
    rw [← ENNReal.ofReal_mul (by positivity), ENNReal.one_le_ofReal]
    have hpow : r ^ (-(d : ℝ) - α) ≤ ‖p.1 - p.2‖ ^ (-(d : ℝ) - α) :=
      Real.rpow_le_rpow_of_nonpos hn hclose hexp
    have hrpow : r ^ ((d : ℝ) + α) * r ^ (-(d : ℝ) - α) = 1 := by
      rw [← Real.rpow_add hr]; norm_num
    have hrp : (0 : ℝ) < r ^ ((d : ℝ) + α) := Real.rpow_pos_of_pos hr _
    calc (1 : ℝ) = r ^ ((d : ℝ) + α) * r ^ (-(d : ℝ) - α) := hrpow.symm
      _ ≤ r ^ ((d : ℝ) + α) * ‖p.1 - p.2‖ ^ (-(d : ℝ) - α) :=
          mul_le_mul_of_nonneg_left hpow hrp.le
      _ = Λ * r ^ ((d : ℝ) + α) * (Λ⁻¹ * ‖p.1 - p.2‖ ^ (-(d : ℝ) - α)) := by
          rw [show Λ * r ^ ((d : ℝ) + α) * (Λ⁻¹ * ‖p.1 - p.2‖ ^ (-(d : ℝ) - α))
              = (Λ * Λ⁻¹) * (r ^ ((d : ℝ) + α) * ‖p.1 - p.2‖ ^ (-(d : ℝ) - α)) from by ring,
            mul_inv_cancel₀ (ne_of_gt hΛ), one_mul]
  calc ENNReal.ofReal ((f p.2 - f p.1) ^ 2)
      = ENNReal.ofReal ((f p.2 - f p.1) ^ 2) * 1 := (mul_one _).symm
    _ ≤ ENNReal.ofReal ((f p.2 - f p.1) ^ 2) *
          (ENNReal.ofReal (Λ * r ^ ((d : ℝ) + α)) * k p.1 p.2) :=
        mul_le_mul' le_rfl (le_trans hgeone (mul_le_mul' le_rfl hklow))
    _ = ENNReal.ofReal (Λ * r ^ ((d : ℝ) + α)) *
          (ENNReal.ofReal ((f p.2 - f p.1) ^ 2) * k p.1 p.2) := by ring


/-- Two points share a tile exactly when they lie in a common half-closed cube. -/
theorem sameTile_eq_iUnion {h : ℝ} (hh : 0 < h) :
    sameTile d h = ⋃ n : Fin d → ℤ,
      halfClosedCube h (latticePt d h n) ×ˢ halfClosedCube h (latticePt d h n) := by
  ext p
  constructor
  · intro hp
    refine Set.mem_iUnion.mpr ⟨fun i => round (p.1 i / h), ?_, ?_⟩
    · exact mem_halfClosedCube_stepIndex hh p.1
    · have : latticePt d h (fun i => round (p.1 i / h)) = stepIndex d h p.2 := by
        rw [show latticePt d h (fun i => round (p.1 i / h)) = stepIndex d h p.1 from rfl, hp]
      rw [this]
      exact mem_halfClosedCube_stepIndex hh p.2
  · intro hp
    obtain ⟨n, hn⟩ := Set.mem_iUnion.mp hp
    have h1 := stepIndex_eq_of_mem hh (latticePt_mem_scaledLattice h n) hn.1
    have h2 := stepIndex_eq_of_mem hh (latticePt_mem_scaledLattice h n) hn.2
    exact h1.trans h2.symm

theorem measurableSet_sameTile {h : ℝ} (hh : 0 < h) : MeasurableSet (sameTile d h) := by
  rw [sameTile_eq_iUnion hh]
  exact MeasurableSet.iUnion fun n =>
    (measurableSet_halfClosedCube h _).prod (measurableSet_halfClosedCube h _)

/-- **The cone part of the modulus `A_h` is bounded uniformly in `h`.**

For any measurable set `A` of pairs lying in a common tile of the `h`-tiling and
seeing each other's cones, the flat `L²` oscillation over `A` is at most
`Λ d^{(d+α)/2} h^{d+α}` times `|f|²_{H_k}`. Dividing by `h^d` (the tile volume)
and by `h^α` leaves a bound independent of `h`: the quantity

  `h^{-α}‖f − E_h f‖²_{L²(B*)}`

is, in its cone-restricted part, already controlled by `|f|²_{H_k(B*)}`. What the
open statement needs is the same for the off-cone part — the oscillation inside a
single tile between points that do not see each other's cones. -/
theorem oscillation_sameTile_le_form {Γ : Configuration (EuclideanSpace ℝ (Fin d))}
    {α Λ : ℝ} {k : EuclideanSpace ℝ (Fin d) → EuclideanSpace ℝ (Fin d) → ℝ≥0∞}
    (hk : KernelBounds Γ α Λ k) (hα : 0 ≤ α) (hd : 0 < d) {h : ℝ} (hh : 0 < h)
    (f : EuclideanSpace ℝ (Fin d) → ℝ) (Ω : Set (EuclideanSpace ℝ (Fin d)))
    {A : Set (EuclideanSpace ℝ (Fin d) × EuclideanSpace ℝ (Fin d))} (hAm : MeasurableSet A)
    (hA : A ⊆ sameTile d h ∩ coneSet Γ ∩ Ω ×ˢ Ω) :
    ∫⁻ p in A, ENNReal.ofReal ((f p.2 - f p.1) ^ 2)
      ≤ ENNReal.ofReal (Λ * (Real.sqrt d * h) ^ ((d : ℝ) + α)) * form Ω k f := by
  have hsd : 0 < Real.sqrt d := Real.sqrt_pos.mpr (by exact_mod_cast hd)
  refine le_trans (lintegral_sq_le_form_of_close hk hα (mul_pos hsd hh) f hAm ?_) ?_
  · intro p hp
    exact ⟨norm_sub_le_of_sameTile hh (hA hp).1.1, (hA hp).1.2⟩
  · exact mul_le_mul' le_rfl (lintegral_mono_set (fun p hp => (hA hp).2))


/-- The companion of `lintegral_ball_rpow_lt_top` at infinity: `‖u‖^γ` is
integrable off a ball as soon as `γ < −d`. Both are needed by any localisation
of the chaining estimates, where a cutoff produces one integral of each kind. -/
theorem lintegral_compl_ball_rpow_lt_top (hd : 0 < d) {r γ : ℝ} (hr : 0 < r)
    (hγ : γ < -(d : ℝ)) :
    ∫⁻ u in {u : EuclideanSpace ℝ (Fin d) | r < ‖u‖}, ENNReal.ofReal (‖u‖ ^ γ) < ∞ := by
  have hdim : Module.finrank ℝ (EuclideanSpace ℝ (Fin d)) = d := by simp
  have hnt : Nontrivial (EuclideanSpace ℝ (Fin d)) := by
    rw [← Module.finrank_pos_iff (R := ℝ), hdim]; exact hd
  have hdcast : ((d - 1 : ℕ) : ℝ) = (d : ℝ) - 1 := by
    have h1 : 1 ≤ d := hd
    push_cast [Nat.cast_sub h1]
    ring
  have hexp : ((d - 1 : ℕ) : ℝ) + γ < -1 := by rw [hdcast]; linarith
  -- the radial integrand
  have hrad : IntegrableOn
      (fun y : ℝ => y ^ (Module.finrank ℝ (EuclideanSpace ℝ (Fin d)) - 1) •
        (Set.Ioi r).indicator (fun y : ℝ => y ^ γ) y) (Set.Ioi 0) volume := by
    rw [hdim]
    have hcongr : ∀ y ∈ Set.Ioi (0 : ℝ),
        y ^ (d - 1) • (Set.Ioi r).indicator (fun y : ℝ => y ^ γ) y
          = (Set.Ioi r).indicator (fun y : ℝ => y ^ (((d - 1 : ℕ) : ℝ) + γ)) y := by
      intro y hy
      by_cases hyr : y ∈ Set.Ioi r
      · rw [Set.indicator_of_mem hyr, Set.indicator_of_mem hyr, smul_eq_mul,
          ← Real.rpow_natCast y (d - 1), ← Real.rpow_add hy]
      · rw [Set.indicator_of_notMem hyr, Set.indicator_of_notMem hyr, smul_zero]
    refine (integrableOn_congr_fun hcongr measurableSet_Ioi).mpr ?_
    rw [integrableOn_indicator_iff measurableSet_Ioi]
    have hinter : Set.Ioi r ∩ Set.Ioi (0 : ℝ) = Set.Ioi r := by
      rw [Set.inter_eq_left]
      exact Set.Ioi_subset_Ioi hr.le
    rw [hinter]
    exact integrableOn_Ioi_rpow_of_lt hexp hr
  have hint : Integrable
      (fun u : EuclideanSpace ℝ (Fin d) => (Set.Ioi r).indicator (fun y : ℝ => y ^ γ) ‖u‖)
      volume :=
    (integrable_fun_norm_addHaar volume
      (f := fun y : ℝ => (Set.Ioi r).indicator (fun y : ℝ => y ^ γ) y)).mpr hrad
  have hfin := hint.hasFiniteIntegral
  have hSm : MeasurableSet {u : EuclideanSpace ℝ (Fin d) | r < ‖u‖} :=
    measurableSet_lt measurable_const measurable_norm
  refine lt_of_le_of_lt ?_ hfin
  calc ∫⁻ u in {u : EuclideanSpace ℝ (Fin d) | r < ‖u‖}, ENNReal.ofReal (‖u‖ ^ γ)
      = ∫⁻ u in {u : EuclideanSpace ℝ (Fin d) | r < ‖u‖},
          ‖(Set.Ioi r).indicator (fun y : ℝ => y ^ γ) ‖u‖‖ₑ := by
        refine setLIntegral_congr_fun hSm fun u hu => ?_
        rw [← ofReal_norm, Set.indicator_of_mem (show ‖u‖ ∈ Set.Ioi r from hu),
          Real.norm_eq_abs, abs_of_nonneg (Real.rpow_nonneg (norm_nonneg u) γ)]
    _ ≤ ∫⁻ u, ‖(Set.Ioi r).indicator (fun y : ℝ => y ^ γ) ‖u‖‖ₑ :=
        lintegral_mono' Measure.restrict_le_self le_rfl


/-- **The cutoff kernel is integrable.** A Lipschitz cutoff at scale `δ` produces
the factor `min (‖u‖²/δ²) 1` against the jump kernel, and the result is
integrable for every `α ∈ (0,2)` — the small scales by
`lintegral_ball_rpow_lt_top` (the exponent `2 − d − α` exceeds `−d`), the large
ones by `lintegral_compl_ball_rpow_lt_top` (the exponent `−d − α` is below `−d`).

This is the estimate a localisation of the chaining results would run on: it is
what bounds the error made by multiplying `f` by a cutoff. -/
theorem lintegral_cutoff_kernel_lt_top (hd : 0 < d) {δ α : ℝ} (hδ : 0 < δ)
    (hα : 0 < α) (hα2 : α < 2) :
    ∫⁻ u : EuclideanSpace ℝ (Fin d),
        ENNReal.ofReal (min (‖u‖ ^ 2 / δ ^ 2) 1 * ‖u‖ ^ (-(d : ℝ) - α)) < ∞ := by
  have hδ2 : (0 : ℝ) < δ ^ 2 := by positivity
  have hcover : (Set.univ : Set (EuclideanSpace ℝ (Fin d)))
      ⊆ ball (0 : EuclideanSpace ℝ (Fin d)) δ ∪
        {u : EuclideanSpace ℝ (Fin d) | δ / 2 < ‖u‖} := by
    intro u _
    by_cases hu : ‖u‖ < δ
    · exact Or.inl (by simpa [Metric.mem_ball, dist_zero_right] using hu)
    · exact Or.inr (by simp only [Set.mem_ofPred_eq]; linarith [not_lt.mp hu])
  have hmin0 : ∀ u : EuclideanSpace ℝ (Fin d), 0 ≤ min (‖u‖ ^ 2 / δ ^ 2) 1 :=
    fun u => le_min (by positivity) zero_le_one
  -- the small scales
  have hsmall : ∀ u : EuclideanSpace ℝ (Fin d),
      ENNReal.ofReal (min (‖u‖ ^ 2 / δ ^ 2) 1 * ‖u‖ ^ (-(d : ℝ) - α))
        ≤ ENNReal.ofReal ((δ ^ 2)⁻¹) *
          ENNReal.ofReal (‖u‖ ^ (2 - (d : ℝ) - α)) := by
    intro u
    rw [← ENNReal.ofReal_mul (by positivity)]
    refine ENNReal.ofReal_le_ofReal ?_
    rcases eq_or_ne u 0 with rfl | hu
    · simp only [norm_zero]
      rw [show min ((0 : ℝ) ^ 2 / δ ^ 2) 1 = 0 from by norm_num, zero_mul]
      exact mul_nonneg (by positivity) (Real.rpow_nonneg le_rfl _)
    · have hn : 0 < ‖u‖ := norm_pos_iff.mpr hu
      have hpow : ‖u‖ ^ (2 - (d : ℝ) - α) = ‖u‖ ^ (2 : ℕ) * ‖u‖ ^ (-(d : ℝ) - α) := by
        rw [← Real.rpow_natCast ‖u‖ 2, ← Real.rpow_add hn]
        congr 1
        push_cast
        ring
      rw [hpow]
      have h1 : min (‖u‖ ^ 2 / δ ^ 2) 1 ≤ ‖u‖ ^ 2 / δ ^ 2 := min_le_left _ _
      have h2 : (0 : ℝ) ≤ ‖u‖ ^ (-(d : ℝ) - α) := Real.rpow_nonneg hn.le _
      calc min (‖u‖ ^ 2 / δ ^ 2) 1 * ‖u‖ ^ (-(d : ℝ) - α)
          ≤ (‖u‖ ^ 2 / δ ^ 2) * ‖u‖ ^ (-(d : ℝ) - α) := mul_le_mul_of_nonneg_right h1 h2
        _ = (δ ^ 2)⁻¹ * (‖u‖ ^ (2 : ℕ) * ‖u‖ ^ (-(d : ℝ) - α)) := by
            field_simp
  -- the large scales
  have hlarge : ∀ u : EuclideanSpace ℝ (Fin d),
      ENNReal.ofReal (min (‖u‖ ^ 2 / δ ^ 2) 1 * ‖u‖ ^ (-(d : ℝ) - α))
        ≤ ENNReal.ofReal (‖u‖ ^ (-(d : ℝ) - α)) := by
    intro u
    refine ENNReal.ofReal_le_ofReal ?_
    have h1 : min (‖u‖ ^ 2 / δ ^ 2) 1 ≤ 1 := min_le_right _ _
    have h2 : (0 : ℝ) ≤ ‖u‖ ^ (-(d : ℝ) - α) := Real.rpow_nonneg (norm_nonneg u) _
    nlinarith [h1, h2]
  calc ∫⁻ u : EuclideanSpace ℝ (Fin d),
        ENNReal.ofReal (min (‖u‖ ^ 2 / δ ^ 2) 1 * ‖u‖ ^ (-(d : ℝ) - α))
      = ∫⁻ u in Set.univ, ENNReal.ofReal (min (‖u‖ ^ 2 / δ ^ 2) 1 *
          ‖u‖ ^ (-(d : ℝ) - α)) := (setLIntegral_univ _).symm
    _ ≤ ∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) δ ∪
          {u : EuclideanSpace ℝ (Fin d) | δ / 2 < ‖u‖},
          ENNReal.ofReal (min (‖u‖ ^ 2 / δ ^ 2) 1 * ‖u‖ ^ (-(d : ℝ) - α)) :=
        lintegral_mono_set hcover
    _ ≤ (∫⁻ u in ball (0 : EuclideanSpace ℝ (Fin d)) δ,
          ENNReal.ofReal (min (‖u‖ ^ 2 / δ ^ 2) 1 * ‖u‖ ^ (-(d : ℝ) - α)))
        + ∫⁻ u in {u : EuclideanSpace ℝ (Fin d) | δ / 2 < ‖u‖},
          ENNReal.ofReal (min (‖u‖ ^ 2 / δ ^ 2) 1 * ‖u‖ ^ (-(d : ℝ) - α)) :=
        lintegral_union_le _ _ _
    _ < ∞ := by
        refine ENNReal.add_lt_top.mpr ⟨?_, ?_⟩
        · refine lt_of_le_of_lt (lintegral_mono hsmall) ?_
          rw [lintegral_const_mul' _ _ ENNReal.ofReal_ne_top]
          exact ENNReal.mul_lt_top ENNReal.ofReal_lt_top
            (lintegral_ball_rpow_lt_top hd hδ (by linarith))
        · refine lt_of_le_of_lt (lintegral_mono hlarge) ?_
          exact lintegral_compl_ball_rpow_lt_top hd (by linarith) (by linarith)


/-! ## A Lipschitz cutoff

The standard radial cutoff, with the one estimate the jump kernel needs:
`(χ(x) − χ(y))² ≤ min (‖x−y‖²/δ², 1)`, which is exactly the factor
`lintegral_cutoff_kernel_lt_top` integrates. -/

/-- The radial Lipschitz cutoff: `1` on `B_R(x₀)`, `0` off `B_{R'}(x₀)`. -/
noncomputable def cutoff (x₀ : EuclideanSpace ℝ (Fin d)) (R R' : ℝ)
    (x : EuclideanSpace ℝ (Fin d)) : ℝ :=
  min 1 (max 0 ((R' - ‖x - x₀‖) / (R' - R)))

lemma abs_clamp_sub_le (a b : ℝ) : |min 1 (max 0 a) - min 1 (max 0 b)| ≤ |a - b| := by
  refine le_trans (abs_min_sub_min_le_max 1 (max 0 a) 1 (max 0 b)) ?_
  rw [sub_self, abs_zero]
  refine max_le (abs_nonneg _) ?_
  rw [max_comm 0 a, max_comm 0 b]
  exact abs_max_sub_max_le_abs a b 0

lemma cutoff_nonneg (x₀ : EuclideanSpace ℝ (Fin d)) (R R' : ℝ)
    (x : EuclideanSpace ℝ (Fin d)) : 0 ≤ cutoff x₀ R R' x :=
  le_min zero_le_one (le_max_left _ _)

lemma cutoff_le_one (x₀ : EuclideanSpace ℝ (Fin d)) (R R' : ℝ)
    (x : EuclideanSpace ℝ (Fin d)) : cutoff x₀ R R' x ≤ 1 := min_le_left _ _

lemma cutoff_eq_one {x₀ : EuclideanSpace ℝ (Fin d)} {R R' : ℝ} (hRR : R < R')
    {x : EuclideanSpace ℝ (Fin d)} (hx : ‖x - x₀‖ ≤ R) : cutoff x₀ R R' x = 1 := by
  have hδ : 0 < R' - R := by linarith
  have h1 : 1 ≤ (R' - ‖x - x₀‖) / (R' - R) := by
    rw [le_div_iff₀ hδ]
    linarith
  rw [cutoff, max_eq_right (by linarith), min_eq_left h1]

lemma cutoff_eq_zero {x₀ : EuclideanSpace ℝ (Fin d)} {R R' : ℝ} (hRR : R < R')
    {x : EuclideanSpace ℝ (Fin d)} (hx : R' ≤ ‖x - x₀‖) : cutoff x₀ R R' x = 0 := by
  have hδ : 0 < R' - R := by linarith
  have h1 : (R' - ‖x - x₀‖) / (R' - R) ≤ 0 := div_nonpos_of_nonpos_of_nonneg (by linarith) hδ.le
  rw [cutoff, max_eq_left h1, min_eq_right zero_le_one]

/-- The cutoff is `1/(R'−R)`-Lipschitz. -/
lemma abs_cutoff_sub_le {x₀ : EuclideanSpace ℝ (Fin d)} {R R' : ℝ} (hRR : R < R')
    (x y : EuclideanSpace ℝ (Fin d)) :
    |cutoff x₀ R R' x - cutoff x₀ R R' y| ≤ ‖x - y‖ / (R' - R) := by
  have hδ : 0 < R' - R := by linarith
  refine le_trans (abs_clamp_sub_le _ _) ?_
  have hsub : (R' - ‖x - x₀‖) / (R' - R) - (R' - ‖y - x₀‖) / (R' - R)
      = (‖y - x₀‖ - ‖x - x₀‖) / (R' - R) := by field_simp; ring
  rw [hsub, abs_div, abs_of_pos hδ]
  gcongr
  have h := abs_norm_sub_norm_le (y - x₀) (x - x₀)
  have h2 : (y - x₀) - (x - x₀) = y - x := by abel
  rw [h2] at h
  rw [norm_sub_rev x y]
  exact h

/-- **The cutoff estimate.** `(χ(x) − χ(y))²` is at most the factor that
`lintegral_cutoff_kernel_lt_top` integrates against the jump kernel. -/
theorem sq_cutoff_sub_le {x₀ : EuclideanSpace ℝ (Fin d)} {R R' : ℝ} (hRR : R < R')
    (x y : EuclideanSpace ℝ (Fin d)) :
    (cutoff x₀ R R' x - cutoff x₀ R R' y) ^ 2
      ≤ min (‖x - y‖ ^ 2 / (R' - R) ^ 2) 1 := by
  have hδ : 0 < R' - R := by linarith
  have h1 : |cutoff x₀ R R' x - cutoff x₀ R R' y| ≤ ‖x - y‖ / (R' - R) :=
    abs_cutoff_sub_le hRR x y
  have h2 : |cutoff x₀ R R' x - cutoff x₀ R R' y| ≤ 1 := by
    rw [abs_le]
    constructor <;>
      [linarith [cutoff_nonneg x₀ R R' x, cutoff_le_one x₀ R R' y];
       linarith [cutoff_nonneg x₀ R R' y, cutoff_le_one x₀ R R' x]]
  refine le_min ?_ ?_
  · have hm := mul_self_le_mul_self (abs_nonneg (cutoff x₀ R R' x - cutoff x₀ R R' y)) h1
    rw [abs_mul_abs_self] at hm
    calc (cutoff x₀ R R' x - cutoff x₀ R R' y) ^ 2
        = (cutoff x₀ R R' x - cutoff x₀ R R' y) *
          (cutoff x₀ R R' x - cutoff x₀ R R' y) := pow_two _
      _ ≤ (‖x - y‖ / (R' - R)) * (‖x - y‖ / (R' - R)) := hm
      _ = ‖x - y‖ ^ 2 / (R' - R) ^ 2 := by rw [div_mul_div_comm, ← pow_two, ← pow_two]
  · have hm := mul_self_le_mul_self (abs_nonneg (cutoff x₀ R R' x - cutoff x₀ R R' y)) h2
    rw [abs_mul_abs_self] at hm
    calc (cutoff x₀ R R' x - cutoff x₀ R R' y) ^ 2
        = (cutoff x₀ R R' x - cutoff x₀ R R' y) *
          (cutoff x₀ R R' x - cutoff x₀ R R' y) := pow_two _
      _ ≤ 1 * 1 := hm
      _ = 1 := by norm_num

end QFS
